[package]
name = "assert-migrator-is-reversible"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm-migration = { version = "^0.9.0", features = [ "runtime-tokio-rustls", "sqlx-sqlite" ] }
tokio = { version = "^1.21.2", features = ["rt", "macros"] }
