[package]
name = "sea-orm-reversible-migrtion-test"
version = "0.1.0"
edition = "2021"

[dependencies]
sea-orm-migration = { version = "^0.9.0", features = [ "runtime-tokio-rustls", "sqlx-sqlite" ] }
